#!/bin/bash

if [ -f /etc/yum.repos.d/elastix.repo ]; then
   echo "You already have installed Eastix 2.5"
   rm -f /root/StackScript
   exit
else
   wget --no-check-certificate https://codeload.github.com/rmaliza/parachutes/zip/master
   unzip master
   chmod +x parachutes-master/install.sh
   ./parachutes-master/install.sh
fi
